name: sfxr
base: core20
version: 1.2.1
summary: Create sound effects
description: Create sound effects


layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
license: MIT
grade: stable
confinement: strict
apps:
  sfxr:
    extensions: [ gnome-3-38 ]
    command: usr/local/bin/sfxr
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
    plugs:
    - alsa
    - audio-playback
    - home
    - removable-media
    - x11
    - opengl
    - desktop
parts:
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
  sfxr:
    after: [alsa-pulseaudio]
    plugin: autotools
    source: https://github.com/popey/sfxr.git
    source-subdir: sfxr
    override-build: |
      snapcraftctl build
      cp -a "$SNAPCRAFT_PART_SRC/sfxr/images" "$SNAPCRAFT_PART_INSTALL/"
    build-packages:
    - gcc
    - g++
    - libsdl1.2-dev
    - build-essential
    stage-packages:
    - libasound2
    - libasound2-plugins
    - libasyncns0
    - libcaca0
    - libflac8
    - libogg0
    - libpulse0
    - libsdl1.2debian
    - libsndfile1
    - libvorbis0a
    - libvorbisenc2
    - libx11-6
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxext6
    - libdrm2
    - libgl1-mesa-glx
    - libglapi-mesa
    - libglu1-mesa
    - libslang2
    - libx11-xcb1
    - libxcb-dri2-0
    - libxcb-dri3-0
    - libxcb-glx0
    - libxcb-present0
    - libxcb-sync1
    - libxdamage1
    - libxfixes3
    - libxshmfence1
    - libxxf86vm1
    - freeglut3
